title: "Joel's IT Portfolio"
description: "Projects, experiences, and experiments in IT."
theme: minima
markdown: kramdown

# URL settings
baseurl: "" # empty for main domain
url: "https://JoelGR365.github.io"

# Build settings
plugins:
  - jekyll-feed
